### ISSUE TITLE
REI addons crashes with latest REI

### ISSUE THREAD

**Issue by UpcraftLP** [shedaniel/REIAddons#1]
REI: 2.3.1.53
REI Addons: 1.0.4
Fabric: 0.2.3.108
Loader: 0.3.7.109
Plugin Loader: 1.14-1.0.6-8

Stacktrace: https://gist.github.com/641a95878d3e1f6bafa0156510197a9d

**Comment by shedaniel** [comment]
This is no longer applicable as rei addons is out of date. I will update it sometime
